# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFqOtvn2nBnMRLYNMUHKsha5Uan1h39Z
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Dados de Fortim, Icapuí e Itaiçaba extraídos da imagem
dados = {
    "Consultas": [
        "CLÍNICA MÉDICA", "CIRURGIA GERAL", "CARDIOLOGIA", "DERMATOLOGIA", "GINECOLOGIA",
        "PRÉ-NATAL RISCO", "GASTROENTEROLOGIA", "MASTOLOGIA", "OTORRINOLARINGOLOGIA", "OFTALMOLOGIA",
        "TRAUMATO-ORTOPEDIA", "UROLOGIA", "PEDIATRIA", "NEUROPEDIATRIA", "COLOPROCTOLOGIA",
        "NEUROLOGISTA", "ENDOCRINOLOGISTA"
    ],
    "Ofertadas": {
        "Aracati": [0, 56, 30, 20, 25, 25, 25, 21, 28, 8, 35, 8, 10, 4, 5, 7, 11],
        "Fortim": [0, 56, 30, 20, 25, 25, 25, 21, 28, 8, 35, 8, 10, 4, 5, 7, 11],
        "Icapuí": [0, 7, 35, 26, 34, 25, 24, 26, 26, 11, 42, 8, 13, 11, 6, 7, 17],
        "Itaíçaba": [0, 3, 14, 11, 12, 17, 16, 8, 12, 4, 15, 4, 5, 2, 3, 3, 9]
    },
    "Agendadas": {
        "Fortim": [0, 51, 25, 18, 25, 29, 24, 9, 26, 4, 36, 8, 4, 4, 6, 4, 11],
        "Icapuí": [0, 9, 48, 31, 34, 25, 30, 11, 22, 9, 42, 7, 6, 11, 5, 6, 17],
        "Itaíçaba": [0, 3, 22, 14, 17, 17, 16, 7, 9, 4, 15, 4, 5, 2, 3, 3, 9]
    },
    "Confirmadas": {
        "Fortim": [0, 51, 21, 16, 18, 25, 23, 9, 28, 4, 36, 7, 4, 3, 5, 4, 9],
        "Icapuí": [0, 9, 23, 20, 36, 25, 30, 11, 22, 4, 41, 7, 5, 11, 3, 4, 7],
        "Itaíçaba": [0, 3, 14, 12, 14, 16, 13, 7, 12, 4, 13, 3, 4, 2, 3, 3, 5]
    }
}

# Função para gerar o gráfico
def gerar_grafico(cidade):
    consultas = dados["Consultas"]
    ofertadas = dados["Ofertadas"][cidade]
    agendadas = dados["Agendadas"][cidade]
    confirmadas = dados["Confirmadas"][cidade]

    x = np.arange(len(consultas))
    largura = 0.25

    fig, ax = plt.subplots(figsize=(14, 6))
    ax.bar(x - largura, ofertadas, width=largura, label='Ofertadas', color='royalblue')
    ax.bar(x, agendadas, width=largura, label='Agendadas', color='firebrick')
    ax.bar(x + largura, confirmadas, width=largura, label='Confirmadas', color='forestgreen')

    for i in range(len(x)):
        ax.text(x[i] - largura, ofertadas[i] + 1, str(ofertadas[i]), ha='center', va='bottom', fontsize=8)
        ax.text(x[i], agendadas[i] + 1, str(agendadas[i]), ha='center', va='bottom', fontsize=8)
        ax.text(x[i] + largura, confirmadas[i] + 1, str(confirmadas[i]), ha='center', va='bottom', fontsize=8)

    ax.set_title(f'Consultas Especializadas - {cidade}', fontsize=14)
    ax.set_xticks(x)
    ax.set_xticklabels(consultas, rotation=45, ha='right', fontsize=9)
    ax.legend()
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    return fig

# Gerar gráficos para Fortim, Icapuí e Itaiçaba
fig_fortim = gerar_grafico("Fortim")
fig_icapui = gerar_grafico("Icapuí")
fig_itaicaba = gerar_grafico("Itaíçaba")

# Salvar como PDF
pdf_path = "/mnt/data/Consultas_Cidades.pdf"
fig_fortim.savefig(pdf_path, format='pdf')
fig_icapui.savefig(pdf_path, format='pdf', bbox_inches='tight')
fig_itaicaba.savefig(pdf_path, format='pdf', bbox_inches='tight')

plt.close('all')

pdf_path

